name: Microservice test pipeline

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: copy code to machine
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Buil image and push to docker hub
              working-directory: ./bisi
              run: |
                docker build -t ${{ vars.DOCKERHUB_USERNAME }}/ndubuisi .
                docker push ${{ vars.DOCKERHUB_USERNAME }}/ndubuisi


